name: Downstream Builds

on:
  issue_comment:
    types: [created]
  pull_request:
    branches: [master]
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello from a downstream build
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  add-downstream-check:
    name: downstream builds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "downstream_build",
            head_sha: "${{ github.sha }}",
            status: "in_progress"
          })
