name: Downstream Builds

on:
  issue_comment:
    types: [created]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo test downstream project
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
