name: Pull Request Workflows
on:
  pull_request:

jobs:
  pull-request-event:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.labels.*.name, 'ci-downstream')"
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo "It worked"
