name: Pull Request Edited Workflow

on:
  pull_request:
    types: [edited]

jobs:
  pull-request-edited-workflow:
    name: pull request edited
    if: "github.event.changes.title.from != '' && startsWith(github.event.pull_request.title, '[ci-downstream]')"
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
