name: Pull Request Edited Workflow

on:
  pull_request:
    types: [edited]

jobs:
  pull-request-edited-workflow:
    name: pull request edited
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
